ALTER TABLE "Client" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Client" ADD COLUMN "deactivatedAt" TIMESTAMP(3);

ALTER TABLE "Car" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Car" ADD COLUMN "deactivatedAt" TIMESTAMP(3);
